# Generated by Django 4.1.2 on 2022-10-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock_Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='starts_in',
        ),
        migrations.AddField(
            model_name='room',
            name='desc',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='ends_in',
            field=models.DateField(),
        ),
    ]
