# Generated by Django 3.2.6 on 2022-10-07 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('consultant_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('image_field', models.ImageField(max_length=500, upload_to='Images/')),
                ('rating', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('meet_id', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('reg_consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.consultant')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.AddField(
            model_name='consultant',
            name='consultant_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Consultant', to='User.profile'),
        ),
    ]
