# Generated by Django 4.1.2 on 2022-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="consultant",
            field=models.BooleanField(default=False),
        ),
    ]
