# Generated by Django 4.1.2 on 2022-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_profile_consultant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_field",
            field=models.ImageField(upload_to="Images"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
