# Generated by Django 4.1.2 on 2022-10-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_remove_profile_email_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="consultant_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
