# Generated by Django 4.1.2 on 2022-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_alter_consultant_consultant_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.TextField(default=""),
        ),
    ]
