# Generated by Django 4.1.2 on 2022-10-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_blogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="upvotes",
        ),
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="User.consultant"
            ),
        ),
    ]
