# Generated by Django 4.1.2 on 2022-10-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0008_remove_blogs_upvotes_alter_blogs_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to="User.consultant",
            ),
        ),
    ]
